### ISSUE TITLE
Event Types are overridden after duplicating a scenario

### ISSUE THREAD

**Issue by mwarger** [mattpocock/sextant#28]
Some kind of issue exists when creating new events.  When running through the Success case for Get User, the USER event 
 type was not created.  I had to delete the event node using the X button and redo it to get the Event payload to show up properly.

Suggested labels: `Recipes`

**Comment by mwarger** [comment]
More details: 

This appears to happen when Duplicating a Scenario.  

Steps to recreate:

- Create a scenario
![image](https://user-images.githubusercontent.com/686823/99193547-5ce70900-273f-11eb-96c2-fdf8a56ad14d.png)
- at this point, you should have two event types
![image](https://user-images.githubusercontent.com/686823/99193574-8011b880-273f-11eb-883b-bda16372c50d.png)

- Duplicate it
- Edit the failure case:
![image](https://user-images.githubusercontent.com/686823/99193597-afc0c080-273f-11eb-91fb-3547d6db850a.png)

- at this point, the event payload for user has been overwritten by editing the corresponding case in the duplicated scenario:
![image](https://user-images.githubusercontent.com/686823/99193614-c5ce8100-273f-11eb-8803-e5bbc3074848.png)

**Comment by mattpocock** [comment]
The fix for this is: if there are more than one event of the same name when you update an event name, create a new event instead.
